### ISSUE TITLE
Does not deobfuscate clouflare challenge.

### ISSUE THREAD

**Issue by gituser-rs** [ZacharyHampton/cf-deobfuscator#1]
Hello. I am not sure if you gonna update it, but it fails on Cloudflare JS Challenge, by just going into endless loop on string shuffling function. 

And personal question: how you learnt deobfuscation of JavaScript files, maybe there are guides/books?

**Comment by ZacharyHampton** [comment]
I plan on finishing this eventually, just been working on other projects in between starting this.

So, I will fix these issues. Regarding where you can learn, I've learned by reading chat for a long time in the sneaker development discord. Some of them also have blogs, such as this one, [blog](https://steakenthusiast.github.io), that helped when it came time to writing my first tool.

**Comment by gituser-rs** [comment]
> I plan on finishing this eventually, just been working on other projects in between starting this.
> 
> So, I will fix these issues. Regarding where you can learn, I've learned by reading chat for a long time in the sneaker development discord. Some of them also have blogs, such as this one, [blog](https://steakenthusiast.github.io), that helped when it came time to writing my first tool.

Thank you!
